version: '3.9'
services:
  backend:
    build:
      context: ./backend
    container_name: car_rental_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: car_rental_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: car_rental_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: car_rental
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      -  "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
